# Generated by Django 3.0.7 on 2020-06-06 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Song2',
            fields=[
                ('song_id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Class')),
            ],
        ),
    ]
